### ISSUE TITLE
Chrome [Android Mobile] - Game will not display properly when returning from sleep mode.

### ISSUE THREAD

**Issue by hmaon** [SpringRoll/SpringRoll#112] opened 2016-07-22 15:43 UTC
When playing a game in landscape orientation, putting the device to sleep and then waking it again causes the game to appear as black box rather than whatever would be drawn to canvas. Sound still plays and taps apparently still register but there are no visuals.

This is on Chrome mobile 51.0.2704.81 on multiple versions of Android (6.0.1 and 5.0.2). It does not happen on Firefox mobile.

**Comment by yanshcherbakovatredspace** [comment] 2016-07-22 15:46
This happens only in landscape orientation or both portrait and landscape orientation?

**Comment by andrewstart** [comment] 2016-07-22 20:01
Also, what are you using for a renderer? EaselJS or PixiJS?

**Comment by hmaon** [comment] 2016-07-23 17:06
EaselJS, only in landscape orientation.

**Comment by yanshcherbakovatredspace** [comment] 2016-08-16 13:31
@hmaon It seems that the problem is somewhat intermittent. Does this happen if you run the game on it's own, as in without Springroll Studio or Springroll Connect?

**Comment by lmckeen** [comment] 2016-08-16 14:42
I do not have access to the exact specified devices listed above, but I tested it with a Galaxy s6, Moto X and a Nexus 7 without being able to reproduce the issue

**Comment by yanshcherbakovatredspace** [comment] 2016-08-16 14:45
@hmaon Could you provide a step-by-step procedure to reproduce this issue consistently? It seems to be intermittent and therefore difficult to pin down the problem, but if you can reproduce it consistently on your end then any additional information that you provide will help us trace it.

**Comment by yanshcherbakovatredspace** [comment] 2016-08-19 16:08
@hmaon We've tested on a Nexus 5 simulator in landscape mode but still not able to reproduce. This could be a game level issue. Would you be able to share a code snippet or zip a demo?

**Comment by yanshcherbakovatredspace** [comment] 2016-08-23 21:47
@hmaon Have you been able to resolve this issue? Any news?

**Comment by hmaon** [comment] 2016-08-29 20:56
@yanshcherbakovatredspace Hi, sorry to leave you hanging here. We resolved it as "ship with" a while back and have wrapped up the project. 

The steps to reproduce the problem were simple, iirc:
1. open game in mobile browser, flip phone sideways (landscape)
2. lock phone with power button
3. unlock phone
4. observe as the image rotates and then goes black

**Comment by jeremymccurdy-redspace** [comment] 2024-10-11 17:57
This is a SpringRoll 1 issue, closing

**Closed by jeremymccurdy-redspace** 2024-10-11 17:57 UTC
Labels: bug
