### ISSUE TITLE
The PageVisibilityPlugin is disabled in games served via an iframe without a SpringRoll container

### ISSUE THREAD

**Issue by chipbell4** [SpringRoll/SpringRoll#149] opened 2017-07-19 16:47 UTC
I believe the regression occured at d2c4a5f2e.

When a game is hosted via an iframe, the code [here](https://github.com/SpringRoll/SpringRoll/blob/master/src/container-client/ContainerClientPlugin.js#L213) is ran (because `springroll.Application.instance.container.supported === true` [when there's an iframe](https://github.com/SpringRoll/Bellhop/blob/dd4c587ac37aa451c13947fc2d7d6d35b0266de4/src/Bellhop.js#L221)).

This causes the `PageVisibilityPlugin` to [be disabled](https://github.com/SpringRoll/SpringRoll/blob/master/src/core/PageVisibilityPlugin.js#L37) as a result.

It appears the reasoning is that if the game is in an iframe, then it's assumed a container is on the other side to forward visibility changes via the [FocusPlugin](https://github.com/SpringRoll/SpringRollContainer/blob/master/src/container/plugins/FocusPlugin.js). However, in some games this is not the case.

**Comment by andrewstart** [comment] 2017-07-19 17:30
If I recall correctly, we would have done this on purpose, because without an actual container on the other side of the iframe, you end up with odd behavior like clicking on the parent page pausing the game which is often not desirable.

**Comment by chipbell4** [comment] 2017-07-19 20:39
That makes sense, but why would you want to listen to the `blur` event in the first place? Why not _only_ listen to `visibilitychange` and ignore `blur` altogether? In the case where the game isn't iframed, you won't get a blur event at all. And, in the case where the game is iframed we don't want `blur` anyways to trigger false positives.

Is there some old browser support that we're maintaining by listening to blur? I noticed that the `FocusPlugin` in the Container is triggering a blur to cause the game to pause (I think), but we could easily use a Bellhop event to trigger the pause.

**Comment by chipbell4** [comment] 2017-07-19 20:40
Oh! Are you saying that sometimes clicking outside the iframe triggers `visibilitychange`?

**Comment by andrewstart** [comment] 2017-07-19 21:41
It has been a long time since I have dealt with that issue, so I don't fully recall if iframe focus triggers visibilitychange.

**Comment by bigtimebuddy** [comment] 2017-07-19 21:54
IE9 does not support page visibility API so the blur focus was an attempt to manage focus of the iframe. This interaction is complex and not having a container was not really a use-case we considered when making. Is there a reason why a container can't be used here?

**Comment by tslepian** [comment] 2017-07-20 16:56
The games Sesame has made with PBS using SpringRoll need to function on both our sites. The Sesame Site https://www.sesamestreet.org/ does not currently have this container (and were hoping to not have to implement it).

**Comment by tslepian** [comment] 2017-07-21 15:58
so any chance to address this issue if a site does not have the container?

**Comment by bigtimebuddy** [comment] 2017-07-21 16:17
This use-case wasn't a requirement when we designed SpringRoll. To my knowledge, there is not a solution to allow PageVisibility functionality when not embedded with a SpringRollContainer. PageVisibility requires communication with the host page in order to function properly across all supported browsers. I would suggest [adding the Container](https://github.com/SpringRoll/SpringRollContainer#usage) to the site, which is trivial to implement (2 lines of code) and very low overhead and would solve the issue. Or simply forfeit PageVisibility functionality for these games when played in this context.

**Comment by tslepian** [comment] 2017-07-21 16:37
some of our older Springroll games on our site function fine and pause sound without the container... just so I understand 100%, this issue is appearing now because of recent changes to SpringRoll - correct?

**Comment by bigtimebuddy** [comment] 2017-07-21 17:02
I'm going to pass this off @yanshcherbakovatredspace, since the most recent PRs that changed this functionality seems to be: 

* https://github.com/SpringRoll/SpringRollContainer/pull/5
* https://github.com/SpringRoll/SpringRoll/pull/117

Could be a regression or may have been a corrected flaw in the original design.

**Comment by tslepian** [comment] 2017-07-26 15:33
Hi @yanshcherbakovatredspace - any update on this?

Thanks,
TS

**Comment by jeremymccurdy-redspace** [comment] 2024-10-11 18:00
This is a SpringRoll 1 issue, closing

**Closed by jeremymccurdy-redspace** 2024-10-11 18:00 UTC
