### ISSUE TITLE
Caption hiccup with shared timing?

### ISSUE THREAD

**Issue by gbhkit** [SpringRoll/SpringRoll#220] opened 2019-02-25 20:48 UTC
Is it verboten to have a caption file with an 'end' time equal to the next phrase's 'start' time?
e.g.:
"captionA":[
   {"content":"phrase1", "start":0, "end":1000},
   {"content":"phrase2", "start":1000, "end":2000}
]

I was making them equal like that for expediency (laziness), but it seems that the caption player can hiccup if the update gets called with a time that matches that shared time. I believe it has to do with the < vs. <= comparisons in the updateState():

https://github.com/SpringRoll/SpringRoll/blob/a3ebd6397a7a0f2021733284a67832301ea9f813/src/localization/captions/Caption.js#L72

It's fine if the answer is to make sure they aren't equal; in all of the examples in the README the end values are not the same as the subsequent start values, but there wasn't a note explicitly requiring them to be different, so I wasn't sure if this was bug or feature.

**Comment by andrewstart** [comment] 2019-02-25 22:03
Hmm, this isn't explicitly intended behavior, but I'm not sure whether we should fix this or not. When I was writing captions at CloudKid, I used the CBC's guide on captions, which said that you should have a gap between caption lines, just to give the eyes and brain a better cue that the text changed.

**Comment by chipbell4** [comment] 2019-02-26 15:41
I agree @andrewstart that the values shouldn't match up. I still think we should handle this case anyways, even if it's a validation pass up front to prevent matching end and start times.

**Comment by ericente** [comment] 2019-02-26 19:46
My preference was always to have gapless captions if breaking a single line (especially a single sentence or thought) into multiple sections of captioning. I find gaps in the middle of a thought jarring. Also, I don't see anything about leaving a gap between segments of a caption in the CBC caption style guide. 

SpringRoll Studio's caption creator assigns equal end and start times to two lines dragged to butt up against each other (and does not allow start times before end times of preceding lines). Most of my SpringRoll 1 games have used caption timing like that. These values represent moments in time: the value 1000 should represent either the start or end of the 1000th millisecond of a piece of audio, not the entirety of the time between 1000 and 1001ms. If one caption ends at a specific time and another starts at that same time, that should be valid.

**Comment by ericente** [comment] 2019-02-28 18:16
http://bbc.github.io/subtitle-guidelines/#Gaps

**Comment by chipbell4** [comment] 2019-11-06 16:15
We're jumping on this right now. Here's where we landed: We're going to allow equal end and start times but I agree with @andrewstart that there are editorial/usability reasons for _not_ having abutting captions. However, I believe the library's concern here would not be to enforce that policy.

In short, @902seanryan or I will update here when the PR is up.

**Comment by chipbell4** [comment] 2019-11-07 15:11
This will be resolved by PR #235. I'll update once that's merged to master and released (as `2.0.3`) to NPM.

**Comment by chipbell4** [comment] 2019-11-07 15:51
Should be resolved now

**Closed by chipbell4** 2019-11-07 15:51 UTC
