### ISSUE TITLE
springroll.Button() mis-scaled on iPhones for large (>512px) sprite sheets

### ISSUE THREAD

**Issue by gbhkit** [SpringRoll/SpringRoll#69] opened 2015-11-10 18:47 UTC
It seems that a springroll.Button(image) initialized with a image that is taller than 512 pixels will have its "down" state scaled down on iPhones (tested on iOS 8, in the simulator). Does not appear to be happening on iPads. Also, if the button is created by passing an imagesettings object, the scaling does not occur, it only happens when initiating with an image.

**Comment by bigtimebuddy** [comment] 2015-11-10 19:01
@gbhkit Can you give a screenshot and code sample?

**Comment by andrewstart** [comment] 2015-11-10 19:26
I've seen this before, and I think it is related to the same issue caused by subsampled JPG images - http://stackoverflow.com/questions/11929099/html5-canvas-drawimage-ratio-bug-ios. It doesn't happen all the time, but reliably happens on certain images/image sections, I've noticed. 
I have also noticed that it only happens when you are drawing the bottom edge of the image, so adding a little padding to the bottom of the image that isn't drawn fixes the problem. Alternatively, drawing your image to a canvas, and then using the canvas as a source instead of the original image works as well.

**Comment by gbhkit** [comment] 2015-11-10 19:41
That sounds right. When trying to make a simple test case, I found that not every image of that size fails, but certain ones fail reliably (though again, even the ones that fail don't fail if setting states manually). I don't think adding padding to the image would work in this particular case because the Button class takes the full image height and divides it by three in order to determine the button state sizes, doesn't it? So it would still draw to the bottom?

**Comment by gbhkit** [comment] 2015-11-10 20:18
Yeah actually my workaround (using image settings object instead of just passing an image) may not be 100% reliable either. It worked where I needed it to, but in the test cases it doesn't always - but it does seem to work if the bounding boxes don't draw all the way to the bottom of the image, as @andrewstart suggested.

Seems there are similar issues with some BitmapMovieClips that are using large sprite sheets.

**Comment by gbhkit** [comment] 2015-11-10 20:36
Here are some screenshots of buttons in the clicked state in iOS

![springroll_button_issues_1](https://cloud.githubusercontent.com/assets/11726632/11074953/a17ccb50-87c0-11e5-92fe-783dcd38b1b1.png)
![springroll_button_issues_2](https://cloud.githubusercontent.com/assets/11726632/11074954/a17ee700-87c0-11e5-9164-f8d368e38a57.png)
![springroll_button_issues_3](https://cloud.githubusercontent.com/assets/11726632/11074952/a17c1de0-87c0-11e5-8e32-1c563217870f.png)
![springroll_button_issues_4](https://cloud.githubusercontent.com/assets/11726632/11074951/a17befb4-87c0-11e5-9b37-3e15e40909ac.png)
![springroll_button_issues_5](https://cloud.githubusercontent.com/assets/11726632/11074950/a17bbc1a-87c0-11e5-99cf-89db66acb202.png)

**Comment by gbhkit** [comment] 2015-11-10 20:40
Here's the culprit image; the test case was the EaselJS Template with a few tweaks to TitlePanel.js

![challengemode](https://cloud.githubusercontent.com/assets/11726632/11075031/0782a3f2-87c1-11e5-98ae-2e1594104547.png)

[TitlePanel.js.txt](https://github.com/SpringRoll/SpringRoll/files/31231/TitlePanel.js.txt)

**Comment by yanshcherbakovatredspace** [comment] 2016-06-03 15:43
A work around is available. Closing.

**Closed by yanshcherbakovatredspace** 2016-06-03 15:43 UTC
Labels: bug
