### ISSUE TITLE
Browser (IE) | Game pause on click of address bar while playing and not resuming again.

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#24] opened 2015-08-12 05:17 UTC
Game pause on click of address bar while playing and clicking on game screen the game is not resuming.

Same issue in Kindle Fire HDX (7"), Kindle Fire HDX (8.9) 
Game is running after minimizing the game browser or locking the device
Music and VO stops playing after maximizing the browser, user have to tap the game screen to play it again.
Please advice.

**Comment by praveen4565** [comment] 2015-08-20 15:25
Hi,

Please advice for the above issue.

Thanks

**Comment by bigtimebuddy** [comment] 2015-08-20 22:59
Sounds like there might be a bug with the auto focusing code `springroll.PageVisibility`. We will investigate more. If you want to disable the auto-pausing set the `autoPause` option to `false`. For example:

```js
var app = new Application({
    autoPause: false
})
```

**Comment by yanshcherbakovatredspace** [comment] 2016-06-07 14:43
Unable to reproduce this issue as described. Neither in Kindle or on IE. Closing.

**Comment by yanshcherbakovatredspace** [comment] 2016-06-07 14:44
This issue exists in Internet Explorer, but not on the Kindle.

**Comment by probityrules** [comment] 2016-11-21 20:55
We experienced this same issue in IE. When we set "autoPreventDefault" to `false` in the app's `displayOptions` for IE, we no longer had this problem. Per https://github.com/SpringRoll/SpringRoll/issues/62#issuecomment-168060217

**Comment by jeremymccurdy-redspace** [comment] 2024-10-11 17:54
Closing issue as it is no longer relevant

**Closed by jeremymccurdy-redspace** 2024-10-11 17:54 UTC
Labels: help wanted
