### ISSUE TITLE
Android devices: Audio stops when we minimize the game after a pause (a min or long) and resume

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#58] opened 2015-10-13 10:56 UTC
When we minimize the game for a minute or long and open the game, game resumes but audio will not play in Android devices. 

FrameWork version: 0.3

**Comment by chetansind** [comment] 2015-10-15 07:06
Is there a solution for this issue? Please suggest.

**Comment by bigtimebuddy** [comment] 2015-10-15 12:50
Can you please provide more information, what versions of Android has this been confirmed for? Just the Chrome browser? Could you see if there is a known issue on [SoundJS](https://github.com/createjs/soundjs/issues)?

**Comment by chetansind** [comment] 2015-10-15 14:32
When we minimize the game and check after a long time (minute or long), game continues to play but audio will not work.
We tested in android versions: 4.4.4, 4.4.2 and 4.2.2
We are facing this only in the Chrome browser.
We did not find this in the known issue on SoundJS.

**Comment by chetansind** [comment] 2015-10-20 10:46
Hi, 

Let me know if this information is clear and please suggest for this issue.

Thanks

**Comment by bigtimebuddy** [comment] 2015-10-20 12:44
By "minimize" do you mean that you go to another tab, navigate to another application, or turn off the screen?

**Comment by chetansind** [comment] 2015-10-20 13:10
Yes, correct.

**Comment by bigtimebuddy** [comment] 2015-10-20 13:14
@chetansind All of those scenarios?

**Comment by chetansind** [comment] 2015-10-20 14:01
Yes, in all the mentioned scenarios and also when we change the volume by using device volume control buttons

**Comment by chetansind** [comment] 2015-10-28 08:50
@bigtimebuddy Please suggest. Thanks

**Comment by bigtimebuddy** [comment] 2015-10-28 13:12
We do not have the bandwidth to tackle this bug at this moment. I'd encourage you all to see if you can find a solution/workaround yourselves. I'm going to keep this bug open.

**Comment by probityrules** [comment] 2015-11-04 18:40
Hi All,

We ran into this issue as well. It appears to be an issue with the browser itself in that it drops the WebAudio context after 30 seconds or so if it thinks it's not in use. I created somewhat of a hack to manipulate SoundJS's WebAudioPlugin to work around this bug, if it's of any use to you. It seems to be working for us so far :-)

It's based on the information found here:
 - https://code.google.com/p/chromium/issues/detail?id=518863
 - http://stackoverflow.com/a/33155239

        // TEMP fix for android bug found here: https://code.google.com/p/chromium/issues/detail?id=518863
        // This fix renews the SoundJS WebAudio context so audio still plays after idle according to this: http://stackoverflow.com/a/33155239
        (function () {
            "use strict";

            var lastTime = 0,
                Sound = include("createjs.Sound"),
                WebAudioPlugin = include("createjs.WebAudioPlugin"),
                android = createjs.BrowserDetect.isAndroid,
                handleAndroidWebAudio = function () {
                    var activePlugin = Sound.activePlugin,
                        lastPlugin = null;
                    
                    if (android && (activePlugin instanceof WebAudioPlugin)) {
                        var fixTime = Date.now();
                        
                        if (lastTime && ((fixTime - lastTime) > 30000)) {
                            // Reset context
                            if (window.AudioContext) {
                                WebAudioPlugin.context = new AudioContext();
                            } else if (window.webkitAudioContext) {
                                WebAudioPlugin.context = new webkitAudioContext();
                            }
                            
                            // Reset WebAudioPlugin
                            Sound.registerPlugins([WebAudioPlugin]);
                            
                            // Copy over relevant properties
                            lastPlugin = activePlugin;
                            activePlugin = Sound.activePlugin;
                            activePlugin._audioSources = lastPlugin._audioSources;
                            activePlugin._soundInstances = lastPlugin._soundInstances;
                        }
                        lastTime = fixTime;
                    }
                }
                
            window.handleAndroidWebAudio = handleAndroidWebAudio;
        }());

With the above, you will just need to call `handleAndroidWebAudio()` in your code _before_ playing sfx or VO.

**Comment by andrewstart** [comment] 2015-11-04 18:47
That's a fun little workaround. The only improvement I would make would be to keep track of if audio is playing, as audio that is just looping prevents the audio context from being idle - I wouldn't want to interfere with a working context just because we let music play for a couple minutes with no other sounds.

**Comment by probityrules** [comment] 2015-11-06 22:37
I can see that. Is there an easy way to track this? I think the VOPlayer has a `playing` property, but I'm not sure if there's an easier route for music and sfx than keeping a master tally and decrementing via onComplete handlers or something.

**Comment by andrewstart** [comment] 2015-11-06 22:43
Well, all of the onComplete handlers already run through springroll.Sound, so it wouldn't be that difficult. We would just have to keep track of paused SoundInstances tell Sound to decrement the master tally, and then increment it when it is unpaused to have all of our bases covered.

**Comment by probityrules** [comment] 2015-11-07 01:07
I had a little trouble getting Spring Roll to build this evening so I could test it out, but I posted a possible fix here: https://github.com/gopherwood/SpringRoll/commit/3ecf3a5e56ca81fcd85f96bdc45d6c49ed8ac982

It's slightly aggressive in that it doesn't check time past last played sound, but it does check for any playing sounds before attempting a reset. I went this route to keep it more self-contained.

**Comment by andrewstart** [comment] 2015-11-09 00:38
I've added a fix with a master tally method. I tested it through a number of context replacements, and it seems to work, so I don't think there are any leaks, of memory or device resources.

**Comment by chetansind** [comment] 2015-11-18 12:31
I've added 0.3.18 version in bower.json and tested the build and I found this issue in Nexus 7 android 5.1.1

**Comment by probityrules** [comment] 2015-11-24 01:41
I've found another issue related to this fix. It has worked fine for us on Android when there's no audio playing and on coming back after several minutes audio plays as expected.

However, if audio is playing and the app loses focus such that the audio is paused for some period of time, on returning there's a game-breaking error. This can be tested in Chrome emulating Android by starting a background music clip, clicking outside the window to pause audio and waiting for 30 secs. Clicking back on the window results in an error.

It seems that any currently-playing clips retain a reference to the old Audio Context, such that when they attempt to resume, the closed old context causes them to fail. Specifically it appears that the gainNode and panNode properties of the sound instance are using the old Audio Context.

Maybe open sound instances could be re-instantiated in some manner so that they're using the proper context?

**Comment by andrewstart** [comment] 2015-11-24 15:36
Open sound instances now have their gainNode and panNodes regenerated, in the (upcoming) updates 0.3.20 & 0.4.10. @chetansind, does using the "0.3-hotfixes" branch of SpringRoll instead of a specific version fix this for you?

**Comment by probityrules** [comment] 2016-02-08 19:36
Fortunately, it looks like the underlying issue has been fixed in Android Chrome: https://code.google.com/p/chromium/issues/detail?id=518863

Not sure about the roll-out timeline (M49) but thought I would at least note it here.

**Comment by yanshcherbakovatredspace** [comment] 2016-05-18 13:42
Seems like that the underlying issue in Android Chrome has been released. Closing this bug.

**Closed by yanshcherbakovatredspace** 2016-05-18 13:42 UTC
