### ISSUE TITLE
Internet explorer | Game pause on click of address bar while playing and is not resuming

### ISSUE THREAD

**Issue by shruthims91** [SpringRoll/SpringRoll#32] opened 2015-08-20 09:48 UTC
Game pause on click of address bar while playing and clicking on game screen the game is not resuming.

Same issue in Kindle Fire HDX (7"), Kindle Fire HDX (8.9) 
 Game is running after minimizing the game browser or locking the device
 Music and VO stops playing after maximizing the browser, user have to tap the game screen to play it again.
 Please advice.

**Comment by bigtimebuddy** [comment] 2015-08-20 12:30
Duplicate of #24

**Closed by bigtimebuddy** 2015-08-20 12:30 UTC
